@echo off
cd /d d:\LolaGoldCargo
if not exist .git (
    echo Initializing git repository...
    git init
)

echo Adding remote origin...
git remote add origin https://github.com/Dee0n/GoldCargo24
echo Setting remote URL...
git remote set-url origin https://github.com/Dee0n/GoldCargo24
echo Adding files...
git add .
echo Committing...
git commit -m "Upload project to GitHub"
echo Renaming branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.

